version: "3"
services:
  mongo_db:
    image: 'mongo'
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data-db:/data/db
    networks:
      - web-net
  
  redis_db:
    image: 'redis:alpine'
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - web-net

  fee-micro:
    restart: always
   # image: diegotony/fee-micro:k8s
    build: ./
    ports:
      - "3041:3041"
    environment:
      - MONGO_HOST=mongo_db
      - PORT=3041
      - REDIS_HOST=redis_db
      - MODE=sandbox
      - CLIENT_ID=EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
      - CLIENT_SECRET=EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

    depends_on:
      - mongo_db
      - redis_db
    links:
      - mongo_db
      - redis_db
    networks:
      - web-net
volumes:
  data-db:
networks:
  web-net:
    driver: bridge